package com.sirolf2009.necromancy.bodypart;

import java.util.ArrayList;
import java.util.List;

/**
 * Root JSON document stored as {@code config/necromancy/bodypartconfigs/&lt;path&gt;.json}.
 * Field names stay stable for Gson round-trip from the dev editor.
 */
@SuppressWarnings("unused")
public final class BodypartDefinitionJson {
    /** Must match the bodypart item registry id (e.g. necromancy:zombie_head). */
    public String id = "necromancy:none";
    /**
     * Author-approved JSON: stubs generated by {@link BodyPartConfigManager} write {@code false}; Save-from-disk via the dev block writes {@code true}.
     * When absent on legacy files (predating this field), loaders treat as validated — see {@link BodypartDefinition#fromJson}.
     */
    public Boolean validated;
    public BodypartHitboxJson hitbox = new BodypartHitboxJson(0, 0.5, 0, 0.35, 0.35, 0.35);
    /** Part-local visual offset in blocks; does not affect collision hitbox. */
    public BodypartVisualOffsetJson visualOffset = new BodypartVisualOffsetJson();
    public BodypartFlagsJson flags = new BodypartFlagsJson();
    public List<BodypartAttachmentJson> attachments = new ArrayList<>();

    public BodypartDefinitionJson copy() {
        BodypartDefinitionJson c = new BodypartDefinitionJson();
        c.id = id;
        c.validated = validated;
        c.hitbox = hitbox != null ? hitbox.copy() : new BodypartHitboxJson();
        c.visualOffset = visualOffset != null ? visualOffset.copy() : new BodypartVisualOffsetJson();
        c.flags = flags != null ? flags.copy() : new BodypartFlagsJson();
        c.attachments = new ArrayList<>();
        if (attachments != null) {
            for (BodypartAttachmentJson a : attachments) {
                if (a != null) c.attachments.add(a.copy());
            }
        }
        return c;
    }
}
